export const LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const LOGIN_LOADER = 'LOGIN_LOADER';
export const REGISTER_LOADER = 'REGISTER_LOADER';

export const DELETE_TODO_REQUEST = 'TODO_DELETE_REQUEST';
export const SET_CURRENT_TODO = 'SET_CURRENT_TODO_VALUE';
export const ADD_TODO_REQUEST = 'TODO_ADD_REQUEST';
export const SET_EDIT_TODO = 'EDIT_TODO_VALUE';
export const UPDATE_EDIT_TODO_VALUE = 'UPDATE_EDIT_TODO_VALUE';
export const ADD_NEW_TODO_REQUEST = 'ADD_NEW_TODO_REQUEST';
export const ADDING_ITEM_LOADER = 'ADDING_ITEM_LOADER';
export const DELETE_ITEM_LOADER = 'DELETE_ITEM_LOADER';
